#ifndef CONST_H
#define CONST_H

#define WIDTH 1

#define MAX_CONFIG_PATH_LENGTH 4096
#define MAX_TASK_FIELD_LENGTH 512
#define MAX_QUEUE_SIZE_LIMIT 10000
#define MIN_QUEUE_SIZE 1
#define MAX_FORMATTED_NUMBER_LENGTH 32

#define MAX_CID_LENGTH 128
#define MAX_GATEWAY_LENGTH 256
#define MAX_URL_LENGTH 512
#define BUFFER_SIZE 4096
#define CID_LENGTH 59

#define MAX_PATH_LENGTH 4096
#define MAX_FILENAME_LENGTH 255
#define MAX_EXTENSION_LENGTH 10
#define MAX_TIME_STRING_LENGTH 32
#define MIN_RANDOM_STRING_LENGTH 1
#define MAX_RANDOM_STRING_LENGTH 256
#define DEFAULT_FILENAME_LENGTH 25

#define COSMOS_API_VERSION "2018-12-31"
#define RFC1123_BUFFER_SIZE 64
#define MAX_MAC_SIZE EVP_MAX_MD_SIZE
#define HTTP_STATUS_OK 200
#define HTTP_STATUS_NOT_FOUND 404

#endif // CONST_H
